export const MAX_PLAYSTATION_BONUS = 6000;
export const PLAYSTATION_MULTIPLIER = 2.5; // K
export const PLAYSTATION_CONSTANT_EMISSION_RATE = 2.08;
export const XBOX_MULTIPLIER = 2.5; // K
export const XBOX_CONSTANT_EMISSION_RATE = 2.08;
export const STEAM_DECK_MULTIPLIER = 2; // K
export const STEAM_DECK_CONSTANT_EMISSION_RATE = 1.67;
export const STEAM_WEB_MULTIPLIER = 1.2; // K
export const STEAM_WEB_CONSTANT_EMISSION_RATE = 1.25;
export const NINTENDO_SWITCH_MULTIPLIER = 1.5; // K
export const NINTENDO_SWITCH_CONSTANT_EMISSION_RATE = 1.25;

export const PLAYSTATION_REWARD_CONSTANT_EMISSION = 50; // Rconstant after 90 days i.e. DECAY_THRESHOLD_DAYS
export const DECAY_THRESHOLD_DAYS = 90;

export const ALPHA = 100;
export const DECAY_CONSTANT = 0.0007451; // lambda
export const NORMALIZING_FACTOR = 20.0;
